/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryTrackingUI;

import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.time.LocalDateTime;
import static java.time.LocalDateTime.now;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Cassie Christian
 */
public class InventoryTrackingUI extends javax.swing.JFrame {

//    Connection conn;
//    PreparedStatement pst;
//    ResultSet rs;

    
    public InventoryTrackingUI() {
        initComponents();
    }
//==========================================Attempt at connecting to Access Database=============================================================    
//    public void msConnectDB(JTable JTable1)
//    {
//        try 
//        {
//           Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
//           
//           conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Cassie Christian\\Documents\\CSIS 643\\InventoryTrackingSystem.accdb");
//           Statement st = conn.createStatement();
//           String query = "Select * from InventoryTrackingSystem";
//           rs = st.executeQuery(query);
//        }catch(Exception e)
//        {
//            
//        }
//    }
//==========================================Attempt at connecting to Access Database=============================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        partIDTextBox = new javax.swing.JTextField();
        serialCodeTextBox = new javax.swing.JTextField();
        partNameTextBox = new javax.swing.JTextField();
        categoryNameTextBox = new javax.swing.JTextField();
        dateAddedTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inventoryIDTextBox = new javax.swing.JTextField();
        serialCode2TextBox = new javax.swing.JTextField();
        inventoryDateTextBox = new javax.swing.JTextField();
        inventoryTimeTextBox = new javax.swing.JTextField();
        quantityTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        partsDropList = new javax.swing.JComboBox<>();
        submitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(815, 505));
        setPreferredSize(new java.awt.Dimension(800, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"229KL", "5/7/2023", "12"},
                {"AB501", "5/7/2023", "10"},
                {"D526H", "5/2/2023", "6"},
                {"229KL", "5/4/2023", "20"},
                {"472MM", "5/2/2023", "3"},
                {"RFD21", "4/19/2023", "88"}
            },
            new String [] {
                "Serial Code", "Date", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(inventoryTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 410));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 360, 430));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Inventory");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Part Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Parts:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        partIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partIDTextBoxActionPerformed(evt);
            }
        });

        categoryNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryNameTextBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date Added:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Category Name:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Part Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Part Serial Code:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Part ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serialCodeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(partIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(partNameTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryNameTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateAddedTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialCodeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateAddedTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Quantity:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Inventory Time:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Inventory Date:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Part Serial Code:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Inventory ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(1, 1, 1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inventoryTimeTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(inventoryDateTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serialCode2TextBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryIDTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTextBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialCode2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, 180));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 70, -1));

        partsDropList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Part", "Receptacle", "Electric Wire", "Faucet", "Shower Valve", "Circuit Board", "Compressor", "Lumber", "Nails" }));
        partsDropList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partsDropListActionPerformed(evt);
            }
        });
        getContentPane().add(partsDropList, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, 30));

        submitButton1.setText("Submit");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partsDropListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partsDropListActionPerformed
        if (partsDropList.getSelectedItem().equals("Receptacle"))
        {
            partIDTextBox.setText("1");
            serialCodeTextBox.setText("AB501");
            partNameTextBox.setText("Receptacle");
            categoryNameTextBox.setText("Electric");
            dateAddedTextBox.setText("5/6/2023");
            serialCode2TextBox.setText("AB501");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Electric Wire"))
        {
            partIDTextBox.setText("2");
            serialCodeTextBox.setText("D526H");
            partNameTextBox.setText("Electric Wire");
            categoryNameTextBox.setText("Electric");
            dateAddedTextBox.setText("5/2/2023");
            serialCode2TextBox.setText("D526H");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }

        if (partsDropList.getSelectedItem().equals("Faucet"))
        {
            partIDTextBox.setText("3");
            serialCodeTextBox.setText("229KL");
            partNameTextBox.setText("Faucet");
            categoryNameTextBox.setText("Plumbing");
            dateAddedTextBox.setText("5/4/2023");
            serialCode2TextBox.setText("229KL");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Shower Valve"))
        {
            partIDTextBox.setText("4");
            serialCodeTextBox.setText("472MM");
            partNameTextBox.setText("Shower Valve");
            categoryNameTextBox.setText("Plumbing");
            dateAddedTextBox.setText("5/2/2023");
            serialCode2TextBox.setText("472MM");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Circuit Board"))
        {
            partIDTextBox.setText("5");
            serialCodeTextBox.setText("F76HM");
            partNameTextBox.setText("Circuit Board");
            categoryNameTextBox.setText("Heating and Cooling");
            dateAddedTextBox.setText("5/4/2023");
            serialCode2TextBox.setText("F76HM");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Compressor"))
        {
            partIDTextBox.setText("6");
            serialCodeTextBox.setText("9KI78");
            partNameTextBox.setText("Compressor");
            categoryNameTextBox.setText("Heating and Cooling");
            dateAddedTextBox.setText("5/3/2023");
            serialCode2TextBox.setText("9KI78");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Lumber"))
        {
            partIDTextBox.setText("7");
            serialCodeTextBox.setText("412LL");
            partNameTextBox.setText("Lumber");
            categoryNameTextBox.setText("General Construction");
            dateAddedTextBox.setText("4/28/2023");
            serialCode2TextBox.setText("412LL");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
        if (partsDropList.getSelectedItem().equals("Nails"))
        {
            partIDTextBox.setText("8");
            serialCodeTextBox.setText("RFD21");
            partNameTextBox.setText("Nails");
            categoryNameTextBox.setText("General Construction");
            dateAddedTextBox.setText("4/19/2023");
            serialCode2TextBox.setText("RFD21");
            inventoryDateTextBox.setText("5/7/2023");
            inventoryIDTextBox.setText("6");
        }
        
    }//GEN-LAST:event_partsDropListActionPerformed

    private void partIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partIDTextBoxActionPerformed

    }//GEN-LAST:event_partIDTextBoxActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
        DefaultTableModel model;
        String serial = "";
        String date = "";
        String quantity = "";
    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
//===========Attempt at creating the functionality of the submit button so that a new row would be created with each submit=================
        serial = serialCode2TextBox.getText();
        date = inventoryDateTextBox.getText();
        quantity = quantityTextBox.getText();
        
        JTable table1 = new JTable();
        table1.setModel(new DefaultTableModel());
//        table1.addRow();
//        var table = new JTable(new DefaultTableModel(new Object[]{"Serial Number","Date","Quantity"}));
//        DefaultTableModel model = (DefaultTableModel) table.getModel();
//        model.addRow(new Object[]{serial, date, quantity});
        
        //table1.addRow(new Object[]{serial, date, quantity});
        
//        String InventoryUpdates = [serialCode2TextBox.getText()];
//,[inventoryDateTextBox.getText()],[quantityTextBox.getText()]);
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void categoryNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryNameTextBoxActionPerformed
private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
//====================================Attempt at connecting to SQL Server=============================================================
//        String url = "jdbc:sqlserver://localhost:1433;databaseName=christianInventoryTracking;integratedSecurity=true;encrypt=true;trustServerCertificate=true;";
//        String username = "LAPTOP-I2TN14IC\\Cassie Christian";
//        String password = "test";
//        
//        try {
//        Connection connection = DriverManager.getConnection(url, username, password);
//        System.out.println("Connected to MS SQL Server");
//        }
//        catch (SQLException e) {
//            System.out.println("Error in connecting to database");
//            e.printStackTrace();
//        }
//====================================Attempt at connecting to SQL Server=============================================================        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryTrackingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryTrackingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryTrackingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryTrackingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryTrackingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryNameTextBox;
    private javax.swing.JTextField dateAddedTextBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField inventoryDateTextBox;
    private javax.swing.JTextField inventoryIDTextBox;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JTextField inventoryTimeTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField partIDTextBox;
    private javax.swing.JTextField partNameTextBox;
    private javax.swing.JComboBox<String> partsDropList;
    private javax.swing.JTextField quantityTextBox;
    private javax.swing.JTextField serialCode2TextBox;
    private javax.swing.JTextField serialCodeTextBox;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
